---
name: Nathan Lally
position: "AVP: Data Science"
address: "281 Gilead Rd, Andover, CT 06250"
phone: (860)287-3415
email: "nathan.lally@hey.com"
github: nathan-lally
linkedin: www.linkedin.com/in/nathan-lally-050764234
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
options(tinytex.verbose = TRUE)
library(vitae)
```


# Experience

__Data Science & Statistics__

 * __AVP Data Science, HSB (Munich Re Group)__, November 2020 - Present
    * Lead a team of data scientists on projects ranging from IoT sensor analytics to analysis of HSB's extensive inspection & engineering services data. We extract insights to support our current lineup of insurance products, but more importantly, to help develop new insurance and innovative risk management products for our clients.
    * Work with business partners in various organizations to develop and deliver client‑facing analytics products and services.
    * Leading efforts to modernize HSB’s data science technology stack, MLOps practices and model deployment
    * Established an ongoing research agreement between HSB and The University of Connecticut’s departments of Statistics and Computer Science focusing on IoT analytics; deploying HSB’s first large scale machine learning system for IoT in production which measures customer responses to alerting systems using causal ML.
    * Assist with the development of methods and models for HSB's insurance data science team.
 * __Senior Data Scientist, HSB (Munich Re Group)__, February 2018 - November 2020
    * Led junior data science talent on technical projects and managed interns
    * Developed core product pricing models
    * Performed IoT sensor data analysis and related insurance product pricing/development, including developing the pricing strategy for HSB's first monetized sensor product (freeze loss warranty)
    * Coordinated and delivered data science education at HSB
 * __Engineering Statistician, Pratt & Whitney (UTC)__, April 2016 - February 2018
     * Performed engineering analysis with statistical/probabilistic models and provided predictive modeling and optimization support to P&W Aftermarket and Finance departments
 * __Adjunct Professor of Biostatistics, University of Connecticut__, January 2017 - May 2017
     * Taught "Introduction to Biostatistics for Health Professionals (AH 3005/5005)" to a class of approximately 100 undergraduate and graduate students in statistics, mathematics, and allied health sciences
 * __Associate Data Scientist, The Hartford Insurance Group__, May 2015 - March 2016
     * Led efforts to build customer retention, issue rate, and customer lifetime value models
 * __Graduate Assistant, University of Connecticut__, August 2014 - May 2015
     * Fully funded GA researching statistical/machine learning methods to predict damages to electrical utility infrastructure
 * __Actuarial & Data Science Internships, The Hartford Insurance Group__, May 2014 - August 2014, December 2014 - January 2015
     * Completed two internships in both actuarial (risk and profitability) and data science (personal lines auto) positions
     
__Defense Contracting__

 * __Various Roles, General Dynamics Electric Boat__, 2008 - 2011
     * Worked in piping design, program planning and process engineering
     * Certified Lean Six Sigma Black Belt
     
# Education

 * __MS Mathematics, University of Connecticut__, 2015
     * Thesis: [The Informative g-Prior vs. Common Reference Priors for Binomial Regression With an Application to Hurricane Electrical Utility Asset Damage Prediction](https://opencommons.uconn.edu/gs_theses/813/)
     * Awards: Google Student Poster Award (In honor of the best posters presented in the fields of Statistics and Probability at the 29th New England Statistical Symposium)
 * __BA Mathematics/Statistics, University of Connecticut__, 2014
 * __BA Political Science, University of Connecticut__, 2007
    * Study abroad in Chiapas, Mexico, 2006
     
# Volunteering & Outreach

 * __[Vice President, New England Statistical Society (NESS)](https://nestat.org/about/structure/)__, June 2020-Present
     * Vice President in charge of the NESS Education Committee
     * Reorganized the committee into four subcommittees focusing on short course development, youth outreach, scholarship funds and ethics in data science education
     * Partnered with the NextGen Committee to establish NESS' new consulting service
     * Co-led the effort to design and deliver the [The New England Statistical Society Scholarships for Underrepresented Minorities ](https://nextgenscholarship.nestat.org/) in 2021
     * Serve on the 2022 New England Statistics Symposium 2022 Program Committee
        * Organizing sessions on ethics for data scientists and data science applications in insuretech
 * __Council Member, New England Statistical Society (NESS)__, May 2017-June 2020
     * Served on the education committee coordinating the society’s educational activities and outreach

# Technology

 * __Programming Languages \& Modeling Frameworks__
    * R, Stan, Python, SQL, PyTorch
 * __Tech__
    * Linux, Git, \LaTeX, Markdown, Microsoft Azure Cloud Services, Databricks

# Publications
  * __[A Custom Unsupervised Approach for Pipe-Freeze Online Anomaly Detection](https://ieeexplore.ieee.org/document/9595720)__,  2021 IEEE 7th World Forum on Internet of Things, 2021
  * __[Modern Methods for Insurance IBNR Reserve Estimation](https://blogisbis.wordpress.com/2019/06/26/modern-methods-for-insurance-ibnr-reserve-estimation/)__, International Society for Business and Industrial Statistics (ISBIS) Blog Corner, 2019
  * __[Estimating Loss Reserves Using Hierarchical Bayesian Gaussian Process Regression with Input Warping](https://www.sciencedirect.com/science/article/pii/S0167668717304523)__, Insurance: Mathematics and Economics, 2018 ([link to pre-print version](https://hartman.byu.edu/files/LallyHartman_GPReserving.pdf))
  * __[Predictive Modeling in Long-Term Care Insurance](https://www.tandfonline.com/eprint/7W2dZajRvYGmTIk4t5bT/full)__, North American Actuarial Journal, 2016 (undergraduate thesis)
  
# Languages

  * English
  * Spanish (conversational)
